<hr style="border: 6px solid#003262;" />

<div align="center">
    <img src= "/assets/content/datax_logos/DataX_blue_wide_logo.png" align="center" width="100%">
</div>


<br>

# **DATA-X:** <br>  m410 - SHALLOW NEURAL NETWORKS; AN INTRODUCTION TO TENSORFLOW V.2

<br>


**Author List (in no particular order):** [Elias Castro Hernandez](https://www.linkedin.com/in/ehcastroh/), [Rajarathnam Balakrishnan](https://www.linkedin.com/in/rajarathnam-balakrishnan-7b447b135/), [Ikhlaq Sidhu](https://ikhlaq-sidhu.com/), [Debbie Yuen](http://www.debbiecyuen.me/), and [Alexander Fred-Ojala](https://www.linkedin.com/in/alexanderfo/) 

**About (TL/DR):** Tensorflow (TF) is an open-source library used for dataflow, differentiable programming, symbolic math ,and machine learning applications such as deep learning neural networks. TF's flexible architecture allows for easy deployment across varied processing platforms. 

**Learning Goal(s):** This notebook covers advanced topics in machine learning. However, it does not require any prior knowledge in machine learning. The goal of this notebook is to teach a user how to deploy a TF model, as well as to provide the user guidance on how to tackle the more nuanced topics. 

**Associated Materials:** To ease the learning curve, we encourage the user of this notebook to view the resources section on the main JupyterLab, and/or review the [Data-X Fundamentals](https://github.com/scetx/datax/tree/master/01-data-x-fundamentals) repo.

**Keywords (Tags):** tensorflow, tensor-flow, tensorflow-tutorial, deep-learning, deep-learning-with-python, neural-networks, data-x, uc-berkeley-engineering 

**Prerequisite Knowledge:** (1) Python, (2) NumPy, (3) Pandas, (4) Linear Algebra, (5) Bash 

**Target User:** Data scientists, applied machine learning engineers, and developers

**Copyright:** Content curation has been used to expedite the creation of the following learning materials. Credit and copyright belong to the content creators used in facilitating this content. Please support the creators of the resources used by frequenting their sites, and social media.


<hr style="border: 4px solid#003262;" />

<a name='Part_table_contents' id="Part_table_contents"></a>



#### CONTENTS

> #### [PART 0: ABOUT AND MOTIVATION](#Part_0)
> #### [PART 1: TENSORS AND OPERATIONS](#Part_1)
> #### [PART 2: TENSORFLOW GRAPHS, AND EXECUTIONS](#Part_2)
> #### [PART 3 (OPTIONAL): TENSORFLOW LINEAR REGRESSION](#Part_3)
> #### [PART 4: WRAP UP AND NEXT STEPS](#Part_4)

#### APPENDIX

> #### [PREREQUISITE KNOWLEDGE AND REQUIREMENTS](#Appendix_1)
> #### [REFERENCES AND ADDITIONAL RESOURCES](#Appendix_2)

<br>


<a id='Part_0'></a>

<hr style="border: 2px solid#003262;" />

#### PART 0

## **ABOUT** AND **MOTIVATION** NEED VIDEO FROM DEBBIE

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
  <a href="">
    <img src="assets/content/images/tensorflow_thumbnail_play-01.png" align="center" width="50%" padding="10px"/>
  </a><br>
</div>

<a id='Part_1'></a>

<hr style="border: 2px solid#003262;" />

#### PART 1

## **TENSORS** AND **OPERATIONS**


<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/tensorflow_thumbnail-01.png" align="center" width="40%" padding="10"><br>
    <br>
    
</div>

<br>

<br>

[**TensorFlow**](https://www.tensorflow.org/) is a cross-platform, end-to-end, open source, platform for efficiently training and deploying machine learning models. TensorFlow offers multiple levels of abstractions, which means you can use high-level API's such as [**Keras**](https://keras.io/) or [**Ludwig**](https://ludwig-ai.github.io/ludwig-docs/index.html) to make things a bit simpler, or even to set up a [**Distribution Strategy**](https://www.tensorflow.org/guide/distributed_training) API on different hardware configurions without having to change the model defintion.

<br>

<strong style="color:red">KEY CONSIDERATION:</strong> Some of the following content may be written for machines running on Linux or Mac operating systems. If you are working on a Windows machine, you will need to enable the Linux Bash Shell, or adjust Shell commands to PowerShell syntax. A tutorial on how to enable the Linux Bash Shell on Windows 10 can be found [here](https://youtu.be/xzgwDbe7foQ).


#### CONTENTS:

> [PART 1.0: TENSORFLOW INSTALLATION NOTES](#Part_1_0)<br>
> [PART 1.1: TENSORFLOW SETUP](#Part_1_1)<br>
> [PART 1.2: TENSORBOARD SETUP](#Part_1_2)<br>
> [PART 1.3: TENSORFLOW TENSORS](#Part_1_3)<br>
> [PART 1.4: TENSORFLOW OPERATIONS](#Part_1_4)<br>
> [PART 1.5 (OPTIONAL): EAGER EXECUTION](#Part_1_5)

<a id='Part_1_0'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.0: TENSORFLOW INSTALLATION NOTES

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/tf_logo_social.png" align="center" width="30%" padding="0px"><br>
    <br>
</div>

<br>

#### **1.0.1 Install Python Development Environment**

___



#### **Install/Update pip3**

https://pip.pypa.io/en/stable/installing/

```bash
    # TensorFlow requires pip version >= 19.0
    $ pip install --upgrade pip 
```

<br>

#### **Install/Update Python 3**

https://www.python.org/downloads/

```bash
    # TensorFlow requires Python 3.5-3.8 
    $ sudo apt-get update && sudo apt-get install python3-dev python3-pip python3-venv python-virtualenv
```

<br>

#### **1.0.2 Create Virtual Environgment (Recommended)**


___

**Create virtual environment**

>On a terminal, or using magic keys, create a new virtual environment using a Python interpreter and creating a ```venv``` directory to hold it

```bash
    $ python3 -m venv venv
```

<br>

**Activate the virtual environment**

```bash
    $ source ./venv/bin/activate      # sh, bash, or zsh

    $ . ./venv/bin/activate.fish       # fish

    $ source ./venv/bin/activate.csh  # csh or tcsh
```

<br>

**Install packages within virtual environment**

When the virtual environment is active, your shell prompt is prefixed by ```(venv)```

> Step 1: reapeat 1.1.1 above, within ```(venv)```<br>

```bash
    # TensorFlow requires pip version >= 19.0
    $ pip install --upgrade pip 
```    

> Step 2: Install TensorFlow2

```bash
    (venv) $ pip install --upgrade tensorflow
```


> Step 3: Verify install

```bash
    (venv) $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

> Step 4: To exit virtual enviroment later

```bash
    (venv) $ pip deactivate
```

<br>

#### **1.0.3 Install TensorFlow on Local Machine (Optional Setup)**

___


**TensorFlow 2**

https://www.tensorflow.org/install/pip

```bash
    # Install using pip
    $ pip install --upgrade tensorflow 
```

<br>

**Verify Installation**

```bash
    $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

<br>

#### **1.0.4 Run TensorFlow in a Container (Optional Setup)**

___

[**Tensorflow Docker images**](https://www.tensorflow.org/install/docker) come pre-configured to run TensorFlow, and provide a virtual environment that is generally the easiest way to set up [**GPU processing**](https://www.tensorflow.org/install/gpu). To learn more about how to use [**Docker**](https://www.tensorflow.org/install/docker/) to separate your applications from your infrastructure, click [here](https://docs.docker.com/get-docker/).

<br>

<a id='Part_1_1'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.1: TENSORFLOW SETUP

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/tf_logo_social.png" align="center" width="30%" padding="0px"><br>
    <br>
</div>

<br>

<br>

[**TensorFlow V.2**](https://www.tensorflow.org/tutorials/quickstart/beginner) removes redundant APIs, and integrates more smoothly with Python via Eager execution. To learn what has changed between versions 1 and 2 of TensorFlow, see [here](https://www.tensorflow.org/guide/effective_tf2). 
<br>

<br> 

#### **1.1.1 General Notebook Setup**
___

In [1]:
# Pyton 2 and 3 support
from __future__ import division, print_function, unicode_literals

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Hide warnings
import warnings
warnings.filterwarnings('ignore')

<br>

**Install TensorFlow:** the following will install TensorFlow using bash. It serves our purposes. However, for detailed installation instructions see [Part 1.1](#Part_1_1)

In [2]:
## Create Virtual Environment ##
! python3 -m venv ./assets/venv

In [3]:
## Activate Virtual Environment ##
! . ./assets/venv/bin/activate

In [4]:
## Ensure pip version >= 19.0 ##
! pip install --upgrade pip 

Requirement already up-to-date: pip in /home/ehch/anaconda3/lib/python3.6/site-packages (20.1.1)


In [5]:
## Ensure TF version >= 2.0 ##
! pip install --upgrade tensorflow

<br>

**Import TensorFlow**

In [6]:
# Canonical way of importing TensorFlow
import tensorflow as tf

___

**Note:** If ```import tensorflow as tf``` doesn't work, TensorFlow is not installed correctly. To resolve the issue see [**build and install error messages**](https://www.tensorflow.org/install/errors)
    
___

In [7]:
# Check tf version, oftentimes tensorflow is not backwards compatible
tf.__version__

'2.2.0'

In [56]:
# Check thatEager Execution is active
tf.executing_eagerly()

True

___

**Note:** TensorFlow V.2 comes with eager execution enabled by default. Eager mode has many benefits, but for our purposes eager mode allows tensor outputs to be viewed without the need of a session -- which may not be necessary depending on your needs. To learn more check out the section on [**eager execution**](#Part_1_5).
___

<a id='Part_1_2'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.2: TENSORBOARD SETUP

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/tensorboard_logo_social.png" align="center" width="30%" padding="0px"><br>
    <br>
</div>

<br>

[**TensorBoard**](https://www.tensorflow.org/tensorboard/get_started) is a tool for measuring and visualizing machine learning workflows. It enables the tracking of important metrics such as [**acuracy**](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Accuracy), it can display summary operations, tensor ouputs, project embeddings to lower dimensional space, and much more. This broad functionality makes TensorBoard an important tool in evaluating, optimizing, and debugging machine learning models. For a five-minute summary of TensorBoard, click [here](https://youtu.be/3bownM3L5zM).

<br>

#### **1.2.1 Load TensorBoard and Associated Libraries**

___

**Load TensorBoard**

In [8]:
## Load TensorBoard notebook extension ##
%load_ext tensorboard

In [9]:
## Load additional libraries needed ##
from datetime import datetime
from IPython.display import clear_output, Image, display, HTML
import os
import pathlib

t = datetime.utcnow().strftime("%Y%m%d%H%M%S") 
log_dir = "tf_logs"
logd = "/tmp/{}/r{}/".format(log_dir, t)

**Clear TensorBoard Logs**

In [10]:
## Clear any logs from previous runs ##
!rm -rf ./logs/

<br>

#### **1.2.2 Confirm TensorBoard is running**

**Note:** The purpose of this section is only to highlight some of the commands for using TensorBoard. The [**MNIST**](https://en.wikipedia.org/wiki/MNIST_database) data set used here, is only for the purposes of highlighting functionality which on this case depends on the [**Keras**](https://keras.io/) library.

___

In [11]:
# from Keras datasets import mnist
mnist = tf.keras.datasets.mnist

# load data into training and testing splits
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# create a sequential model
def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

___

**Note:** Click on the following to learn more about the command:
>[```keras.model.sequential( )```](https://keras.io/api/models/sequential/)<br>
>[```keras.layers.Flatten( )```](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten)<br>
>[```keras.layers.Dense( ) ```](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense)<br>
>[```keras.layers.Dropout( )```](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout)
    
___

**Add Tensorboard callbacks**

In [12]:
# instantiate model class
model = create_model()

# compile model 
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# place logs in a timestamped subdirectory and enable histogram computation with every epoch
log_dir = "logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)


# Fit model
model.fit(x=x_train, 
          y=y_train, 
          epochs=3, 
          validation_data=(x_test, y_test), 
          # Adding 'callbacks=[tensorboard_callback]' to model.fit( ) ensures that logs are created and stored
          callbacks=[tensorboard_callback])

Epoch 1/3
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2187 - accuracy: 0.9347 - val_loss: 0.1027 - val_accuracy: 0.9696
Epoch 2/3
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0968 - accuracy: 0.9707 - val_loss: 0.0803 - val_accuracy: 0.9749
Epoch 3/3
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0689 - accuracy: 0.9790 - val_loss: 0.0678 - val_accuracy: 0.9801


___

**Note:** Click on the following to learn more about the command:
>[```model.compile( )```](https://keras.io/api/models/model/)<br>
>[```callbacks.TensorBoard( )```](https://keras.io/api/callbacks/)<br>
>[```model.fit( ) ```](https://keras.io/api/models/model_training_apis/)
    
___

**Display Tensorboard Logs**

In [13]:
## %tensorboard line magic. In command line run same command without "%" ##
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 4823), started 9:42:13 ago. (Use '!kill 4823' to kill it.)

___
**Note:** if TensorBoard does not load after following the above command, try reloading TensordBoard ```%load_ext tensorboard``` 
___

<a id='Part_1_3'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.3: TENSORFLOW TENSORS

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE-01_scalar_to_tensor.png" align="center" width="50%" padding="10px"><br>
    <br>
</div>

[**Tensors**](https://www.tensorflow.org/api_docs/python/tf/Tensor) are immutable multidimensional arrays for working with data with more than 2-Dimensions. Tensors essentially multilinear maps from vector spaces to real numbers. Hence a tensor can be used to represent scalars, vectors, and matrices. Moreover, tensors are [**highly efficient**](https://realpython.com/numpy-tensorflow-performance/), can be ran on several architectures (CPUs, GPUs, Mobile, and Distributed), and make the calculation of gradients easier -- this is particulary useful as the analytical solution of gradients are extremely tedious to derive. To view the complete list of TensorFlow data types, see [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType).

<br>

#### **1.3.1 tf.constant**

___

<br>

[**Constants**](https://www.tensorflow.org/api_docs/python/tf/constant) are tensors, are initialized directly, and are immutable once created. In order to evaluate them, we have to run them in a [**session**](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Session), shown below, or can be displayed using [**eager execution**](https://www.tensorflow.org/guide/eager) without a session.

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE_01a_scalar.png" align="center" width="10%" padding="10px"><br>
    <br>
    Scalar (Rank-0) Tensor
</div>

In [14]:
# int32 tensors by default
rank_0_tensor = tf.constant(4)
b = tf.constant(5)

In [18]:
rank_0_tensor.numpy()

4

In [19]:
# tensors can also have names (in the computation graph)
named_tensor = tf.constant(7.2, name='my_named_tuple')
named_tensor.numpy()

7.2

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE_01b_vector.png" align="center" width="10%" padding="10px"><br>
    <br>
    Vector (Rank-1) Tensor
</div>

In [20]:
# float vector tensor
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [21]:
# Contant Tensors are immutable
try:
    rank_1_tensor.assign(8)
except:
    print('Cannot assign contstants')

Cannot assign contstants


<br>

#### **1.3.2 tf.Variable**

___

A [**variable**](https://www.tensorflow.org/guide/variable) is the recommended way to represent data manipulated by your program. Variables are usually weights and biases of a model that are optimized during training, they also indicate the degrees of freedom of the model (what model parameters that can change, thus making the model flexible). The following covers how to create, update, and manage instances of [```tf.variable```](https://www.tensorflow.org/api_docs/python/tf/Variable).

In [22]:
# Create variable tensor
var = tf.Variable(3.)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [23]:
# Reassign the value of a Variable
var.assign(4)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

<br>

**Multidimensional Tensors**

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE_01c_matrix.png" align="center" width="10%" padding="10px"><br>
    <br>
    Matrix (Rank-2) Tensor
</div>

In [25]:
# tensors can be n-arrays, and we can specity data type
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [26]:
# we can also create multi dim Variables directly
c = tf.Variable(np.random.randn(3).reshape(3,1)) #reshape
# automatically assings data type
c #

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float64, numpy=
array([[-0.83351955],
       [-1.46177409],
       [ 0.79506919]])>

In [27]:
# Altenatively, we can pass Python Lists or NumPy arrays
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_var = tf.Variable(my_tensor)
my_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [28]:
# view properties of tensor
print('\nname  : ', my_var.name)
print('\ntype  : ', my_var.dtype)
print('\nshape : ', my_var.shape)
print('\ndevice: ', my_var.device)
print("\nAs NumPy: ", my_var.numpy)


name  :  Variable:0

type  :  <dtype: 'float32'>

shape :  (2, 2)

device:  /job:localhost/replica:0/task:0/device:CPU:0

As NumPy:  <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


In [29]:
# Tensor operations
print("\nViewed as a tensor:", tf.convert_to_tensor(my_var))
print("\nIndex of highest value:", tf.argmax(my_var))


Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)


<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE_01d_3D_tensor.png" align="center" width="50%" padding="10px"><br>
    <br>
    3D (Rank-3) Tensor
</div>

In [30]:
# Tensors with 3 or more axes (dimensions)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<br>

**Tensor Variable Assignments**

In [31]:
# This creates a new tensor; it does not reshape my_var.
print("\nCopying and reshaping (this creates a new tensor): ", tf.reshape(my_var, ([1,4])))


Copying and reshaping (this creates a new tensor):  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [32]:
## Sanity Check ##

d = tf.Variable([4.0, 5.5])
# This will keep the same dtype, float32
d.assign([10, 20]) 

# Fails, as it resizes the variable 
try:
  d.assign([1.0, 2.0, 3.0])
except Exception as exc:
  print(f"{type(exc).__name__}: {exc}")

ValueError: Shapes (2,) and (3,) are incompatible


___

**Note:** Calling ```assign( )``` does not, usually, allocate a new tensor -- instead the tensor's memory is reused.

___

In [33]:
## Sanity Check ##

# Create a new variable based on valued of d
e = tf.Variable(d)
# make assignment
d.assign([10, 20]) 

# a and b are different
print(e.numpy())
print(d.numpy())

[10. 20.]
[10. 20.]


In [34]:
# Inplace increase/decrease variable values

f = tf.Variable(3.)
print('\noriginal value: ', f.numpy())
f.assign(10)
print('\nassigned value: ', f.numpy())
print('\nadd 1:', f.assign_add(1.).numpy())
print('\nsubtract 5:', f.assign_sub(5.).numpy())

# same but for arrays
print("\nIncrease/Decrease values in arrays")
print('original value: ',e.numpy())      
print('\nadd [1,4]: ', e.assign_add([1,4]).numpy())  
print('\nsubtract [3,5]', e.assign_sub([3,5]).numpy())  



original value:  3.0

assigned value:  10.0

add 1: 11.0

subtract 5: 6.0

Increase/Decrease values in arrays
original value:  [10. 20.]

add [1,4]:  [11. 24.]

subtract [3,5] [ 8. 19.]


<!--Navigate back to table of contents-->
<div align="left" style="text-align: left; background-color:#003262;">
    <span>
        <hr style="border: 8px solid#003262;" />
        <a style="color:#FFFFFF; background-color:#003262; border:1px solid #FFFFFF; border-color:#FFFFFF;border-radius:0px;border-width:0px;display:inline-block;font-family:arial,helvetica,sans-serif;font-size:24px;letter-spacing:0px;line-height:20px;padding:24px 40px;text-align:left;text-decoration:none; align:left"> 
            <strong>CONCEPT</strong> CHECK 
        </a>        
    </span>

</div>
<!-------------------------------------->

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE_01e_4D_tensor.png" align="center" width="40%" padding="10px"><br>
    <br>
    4D (Rank-4) Tensor
</div>


> **To test your understanding of Tensors, create the above Tensor. For simplicity, make all entries equal to zero and name your tensor as** ```rank_4_tensor``` **.** 


<hr style="border: 2px solid#003262;" />

In [35]:
# your code here




In [36]:
## Sanity Check ##
#print("\nType of elements:", rank_4_tensor.dtype)
#print("\nNumber of dimensions:", rank_4_tensor.ndim)
#print("\nShape of tensor:", rank_4_tensor.shape)
#print("\nElements along axis 0 of tensor:", rank_4_tensor.shape[0])
#print("\nElements along the last axis of tensor:", rank_4_tensor.shape[-1])
#print("\nTotal number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

<!--Navigate back to table of contents-->
<br>
<div alig="right" style="text-align: right">
    <span>
        <a style="color:#FFFFFF; background-color:#003262; border:1px solid #FFFFFF; border-color:#FFFFFF;border-radius:5px;border-width:0px;display:inline-block;font-family:arial,helvetica,sans-serif;font-size:10px;letter-spacing:0px;line-height:10px;padding:10px 20px;text-align:center;text-decoration:none; align:center" href="#Part_table_contents" name="Table of Contents"  id="Part_table_contents"> 
            Table of Contents 
        </a>
    </span>
</div>
<!-------------------------------------->

<br>

#### **1.3.3 (Optional) Lifecycles, naming, and watching**

___

Similar to Python Objects, a ```tf.Variable``` instance has an [**object lifecyle**](https://en.wikipedia.org/wiki/Object_lifetime). For example, when there are no references to a variable it is automatically ignored and deallocated. Variable names are preserved when loading and saving models -- however, there is no need to assign them as variables in in models are uniquely named automatically.

In [37]:
# Altenatively, we can pass Python Lists or NumPy arrays
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [38]:
# Create a and b; they have the same value but are backed by different tensors.
g = tf.Variable(my_tensor, name="Mark")

# A new variable with the same name, but different value
h = tf.Variable(my_tensor + 1, name="Mark")      # Note that the scalar add is broadcast (see intro_NUMPY for details)

# These are elementwise-unequal, despite having the same name
print(g == h)

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


<br>

#### **1.3.4 (Optional) Placing variables and tensors**

___

TensorFlow will always attempt to place tensors and variables on the fastest device compatible with the ```dtype```. However, this too is a process that can be overriden if desired. The following shows an example of such an instance. In particular, a float tensor and variable are placed on a CPU even if a GPU is available -- most variables are placed on a GPU if one is available. For more details on placing variables and tensors, see [here](https://www.tensorflow.org/guide/variable).

In [39]:
with tf.device('CPU:0'):

  # Create some tensors
  i = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  j = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  k = tf.matmul(i, j)

print(k)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


___

**Note:** Placing variables is an important aspect of TF. This is because it is possible to set the location of a variable or tensor on one device, yet do the computation on another device. This may introduce delay when devices communicate with one-another, but should you want to have multiple GPU workers yet only one copy of the variables this approach is worth considering. See [**automatic distribution**](https://www.tensorflow.org/guide/autodiff) for details.


___

In [40]:
with tf.device('CPU:0'):
  l = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  m = tf.Variable([[1.0, 2.0, 3.0]])
    
with tf.device('GPU:0'):
  # Element-wise multiply
  n = l * m

print(n)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)


___

**Note:** [tf.config.set_soft_device_placement](https://www.tensorflow.org/api_docs/python/tf/config/set_soft_device_placement) is on by default. If you run the code above on a device witout a GPU, the multiplication will be ran on the CPU.
    
___

<a id='Part_1_4'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.4: TENSORFLOW OPERATIONS
<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE-02_tensorflow_operation.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

#### **1.4.1 Basic Arithmetic on Tensors**

___

In [41]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[10, 20],
                 [30, 40]]) 

In [42]:
# Addition
print(tf.add(a, b))

tf.Tensor(
[[11 22]
 [33 44]], shape=(2, 2), dtype=int32)


In [43]:
# Alternatively, element-wise addition
print(a + b)

tf.Tensor(
[[11 22]
 [33 44]], shape=(2, 2), dtype=int32)


In [44]:
# Element-wise multiplication
print(tf.multiply(a, b))

tf.Tensor(
[[ 10  40]
 [ 90 160]], shape=(2, 2), dtype=int32)


In [45]:
# Alternatively, element-wise multiplication
print(a * b)

tf.Tensor(
[[ 10  40]
 [ 90 160]], shape=(2, 2), dtype=int32)


In [46]:
# Matrix multiplication
print(tf.matmul(a, b))

tf.Tensor(
[[ 70 100]
 [150 220]], shape=(2, 2), dtype=int32)


In [47]:
# Alternatively, Matrix multiplication
print(a @ b, "\n")

tf.Tensor(
[[ 70 100]
 [150 220]], shape=(2, 2), dtype=int32) 



<br>

#### **1.4.2 Operations on Tensors**

___

In [49]:
c = tf.constant([[3.0, 7.0], [10.0, 2.0]])

In [50]:
# Find the largest value
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [51]:
# Find the index of the largest value
print(tf.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [52]:
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(
[[1.7986210e-02 9.8201376e-01]
 [9.9966466e-01 3.3535014e-04]], shape=(2, 2), dtype=float32)


<br>

#### **1.3.2 Data Selection: Indexing and Slicing a DataFrame**

>[Indexing DataFrames](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#different-choices-for-indexing)<br>
>[Range Slicing DataFrames](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges)

___

**Attribute Access**

1    1.764052
2    0.400157
3    0.978738
Name: a1, dtype: float64

<a id='Part_1_5'></a>

<hr style="border: 1px solid#003262;" />

#### PART 1.5 (OPTIONAL): EAGER EXECUTION

<br>

[**Eager Execution**](https://www.tensorflow.org/guide/eager) is an imperative programming environment for TensorFlow that evaluates operations immediately, without building graphs. Operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models, and it reduces boilerplate as well. To get an overview of eager mode, check out [this](https://youtu.be/qTYQEXsBb_E) video from Google Cloud Platform. 

In [ ]:
# Enable Eager Execution
# tf.enable_eager_execution

In [ ]:
# Sanity Check
# tf.executin_eagerly()

<a id='Part_2'></a>

<hr style="border: 2px solid#003262;" />

#### PART 2

## **TENSORFLOW** GRAPHS, **AND** EXECUTIONS

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas_logo.png" align="center" width="15%" padding="10"><br>
    <br>
</div>

<br>

[**TODO**](https://pandas.pydata.org/pandas-docs/stable/index.html) TODO

#### CONTENTS:

> [PART 2.1: TENSORFLOW COMPUTATION GRAPHS](#Part_2_1)<br>
> [PART 2.1: TENSORFLOW OPERATIONS](#Part_2_2)<br>
> [PART 2.2: TO DO](#Part_2_3)<br>


<a id='Part_2_1'></a>

<hr style="border: 1px solid#003262;" />

#### PART 2.1: TENSORFLOW COMPUTATION GRAPHS
<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/DELETE-03_tensorflow_computation_graph.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<a id='Part_2_1'></a>

<hr style="border: 1px solid#003262;" />

#### PART 2.1:TENSORFLOW OPERATIONS

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas-16.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

#### **2.1.0 Load Packages/Libraries**

___

<br>

#### **2.2.1 Read Data Into DataFrame From CSV File**


___

<br>

#### **2.2.2 Explore the Data**

___

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Admit   24 non-null     object
 1   Gender  24 non-null     object
 2   Dept    24 non-null     object
 3   Freq    24 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 896.0+ bytes


<a id='Part_2_2'></a>

<hr style="border: 1px solid#003262;" />

#### PART 2.2: TO DO

<br>

<!--Navigate back to table of contents-->
<div alig="right" style="text-align: right">
    <span>
        <a style="color:#FFFFFF; background-color:#003262; border:1px solid #FFFFFF; border-color:#FFFFFF;border-radius:5px;border-width:0px;display:inline-block;font-family:arial,helvetica,sans-serif;font-size:10px;letter-spacing:0px;line-height:10px;padding:10px 20px;text-align:center;text-decoration:none; align:center" href="#Part_table_contents" name="Table of Contents"  id="Part_table_contents"> 
            Table of Contents 
        </a>
    </span>
</div>
<!-------------------------------------->

<a id='Part_3'></a>

<hr style="border: 2px solid#003262;" />

#### PART 3 (OPTIONAL)

## **TENSORFLOW** LINEAR **REGRESSION**

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas_logo.png" align="center" width="15%" padding="10"><br>
    <br>
</div>

<br>

[**TODO**](https://pandas.pydata.org/pandas-docs/stable/index.html) TODO

#### CONTENTS:

> [PART 3.1: CONSTRUCTION PHASE](#Part_3_1)<br>
> [PART 3.2: EVALUATION PHASE](#Part_3_2)<br>
> [PART 3.3: ACCURACY COMPARISON](#Part_3_3)

<a id='Part_3_1'></a>

<hr style="border: 1px solid#003262;" />

#### PART 3.1: CONSTRUCTION PHASE

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas-16.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

<a id='Part_3_2'></a>

<hr style="border: 1px solid#003262;" />

#### PART 3.2: EVALUATION PHASE

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas-16.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

<a id='Part_3_3'></a>

<hr style="border: 1px solid#003262;" />

#### PART 3.3: ACCURACY COMPARISON

<br>

<div align="center" style="font-size:12px; font-family:FreeMono; font-weight: 100; font-stretch:ultra-condensed; line-height: 1.0; color:#2A2C2B">
    <img src="/assets/content/images/pandas-16.png" align="center" width="40%" padding="0px"><br>
    <br>
</div>

<br>

<!--Navigate back to table of contents-->
<div alig="right" style="text-align: right">
    <span>
        <a style="color:#FFFFFF; background-color:#003262; border:1px solid #FFFFFF; border-color:#FFFFFF;border-radius:5px;border-width:0px;display:inline-block;font-family:arial,helvetica,sans-serif;font-size:10px;letter-spacing:0px;line-height:10px;padding:10px 20px;text-align:center;text-decoration:none; align:center" href="#Part_table_contents" name="Table of Contents"  id="Part_table_contents"> 
            Table of Contents 
        </a>
    </span>
</div>
<!-------------------------------------->

<a id='Part_4'></a>

<hr style="border: 2px solid#003262;" />

#### PART 4

## **WRAP-UP** AND **NEXT** STEPS


<div align="center">
    <img src= "/assets/content/datax_logos/DataX_icon_wide_logo.png" align="center" width="80%" padding="20">
</div>

<br>

As you may have started to notice, that there is much more than can be done using Flask. Wanting to learn other uses of Flask?  Visit the [**Data-X website**](https://datax.berkeley.edu/) to learn more, or use the following links to topics of interest:

> [TODO (m---): url needed]() TODO TODO TODO <br>
> [TODO (m---): url needed]() TODO TODO TODO <br>
> [TODO (m---): url needed]() TODO TODO TODO



<br>

<br>


<a id='Appendix_1'></a>

<hr style="border: 6px solid#003262;" />


#### APPENDIX I


## PREREQUISITE **KNOWLEDGE** AND **REQUIREMENTS**


[**TODO**](https://pandas.pydata.org/about/) TODO TODO TODO

##### **PYTHON**
This notebook and the executable files are built using [**Python**](https://www.python.org/) and relies on common Python packages (e.g. [**NumPy**](https://numpy.org/)) for operation. If you have a lot of programming experience in a different language (e.g. C/C++/Matlab/Java/Javascript), you will likely be fine, otherwise:

> [**Python (EDX free)**](https://www.edx.org/course?search_query=python)<br>
> [**Python (Coursera free)**](https://www.coursera.org/search?query=python)


##### **NUMPY**
This notebook and the executable files are built using [**Python**](https://www.python.org/) and relies on common Python packages (e.g. [**NumPy**](https://numpy.org/)) for operation. If you have a lot of programming experience in a different language (e.g. C/C++/Matlab/Java/Javascript), you will likely be fine, otherwise:

> [**Python (EDX free)**](https://www.edx.org/course?search_query=python)<br>
> [**Python (Coursera free)**](https://www.coursera.org/search?query=python)


##### **PANDAS**
This notebook and the executable files are built using [**Python**](https://www.python.org/) and relies on common Python packages (e.g. [**NumPy**](https://numpy.org/)) for operation. If you have a lot of programming experience in a different language (e.g. C/C++/Matlab/Java/Javascript), you will likely be fine, otherwise:

> [**Python (EDX free)**](https://www.edx.org/course?search_query=python)<br>
> [**Python (Coursera free)**](https://www.coursera.org/search?query=python)


##### **MACHINE LEARNING PROBLEM FRAMING**
This notebook and the executable files are built using [**Python**](https://www.python.org/) and relies on common Python packages (e.g. [**NumPy**](https://numpy.org/)) for operation. If you have a lot of programming experience in a different language (e.g. C/C++/Matlab/Java/Javascript), you will likely be fine, otherwise:

> [**Python (EDX free)**](https://www.edx.org/course?search_query=python)<br>
> [**Python (Coursera free)**](https://www.coursera.org/search?query=python)


##### **BASH**
This notebook and the executable files are built using [**Python**](https://www.python.org/) and relies on common Python packages (e.g. [**NumPy**](https://numpy.org/)) for operation. If you have a lot of programming experience in a different language (e.g. C/C++/Matlab/Java/Javascript), you will likely be fine, otherwise:

> [**Python (EDX free)**](https://www.edx.org/course?search_query=python)<br>
> [**Python (Coursera free)**](https://www.coursera.org/search?query=python)

<a id='Appendix_2'></a>

<hr style="border: 2px solid#003262;" />

#### APPENDIX II


## **REFERENCES** AND ADDITIONAL **RESOURCES**

<br>


> * [**TensorFlow Tutorials**](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)

> * [**TensorFlow Guide**](https://youtu.be/dcqPhpY7tWk) 

> * [**Introduction to TensorFlow by Andrew Ng and Kian Katanforoosh**](https://cs230.stanford.edu/blog/tensorflow/)

> * [**Deep Learning Illustrated by Jon Krohn, Grant Beyleveld, and Aglae Bassens**](https://www.deeplearningillustrated.com/)

> * [**Hands-On Introduction to TensorFlow 2.0 by Josh Gordon and Amit Patankar**](https://youtu.be/Yyv-ng0_OTU)

> * [**Getting Started with TensorFlow and Deep Learning by Josh Gordon**](https://youtu.be/tYYVSEHq-io)

<!--Navigate back to table of contents-->
<div alig="right" style="text-align: right">
    <span>
        <a style="color:#FFFFFF; background-color:#003262; border:1px solid #FFFFFF; border-color:#FFFFFF;border-radius:5px;border-width:0px;display:inline-block;font-family:arial,helvetica,sans-serif;font-size:10px;letter-spacing:0px;line-height:10px;padding:10px 20px;text-align:center;text-decoration:none; align:center" href="#Part_table_contents" name="Table of Contents"  id="Part_table_contents"> 
            Table of Contents 
        </a>
    </span>
</div>
<!-------------------------------------->

<hr style="border: 6px solid#003262;" />
